### ISSUE TITLE
jekyll-asciidoc: nested page variables problem

### ISSUE THREAD

**Issue by gernotstarke** [arc42/HHGDAC#7]
in Markdown, it's that:

```
header:
  overlay_image: /images/splash/privacy-274694-unsplash.jpg
  caption: "Photo credit: [**Scott Webb**](https://unsplash.com/photos/yekGLpc3vro)"
```

In Asciidoc it's supposed to be:

`:page-header: { overlay_image: /images/splash/get-started-599118-unsplash.jpg }
`

But: If I add the caption variable, the image is not shown any longer:

```
:page-header: { overlay_image: /images/splash/get-started-599118-unsplash.jpg }
:page-header: { caption: "David Iskander"}

```

**Comment by gernotstarke** [comment]
as a workaround, we can fallback to the markdown-based yaml header for the page...

**Comment by rdmueller** [comment]
haven't tested it, but I guess `page-header` is an attribute which gets overwritten through the second statement. The assigned value looks like a map, so maybe something like this works:

    :page-header: { overlay_image: "/images/splash/get-started-599118-unsplash.jpg", caption: "David Iskander"}

**Comment by gernotstarke** [comment]
you're a hero - it (nearly) works...

strangely, we need to include the image-caption link in markdown-syntax, so the final (working) result is:

```
= Ready, Set, Go!
:page-layout: single
:page-permalink: /getstarted
:page-header: { overlay_image: /images/splash/get-started-599118-unsplash.jpg, caption: "[David Iskander](https://unsplash.com/photos/iWTamkU5kiI)" }


== This is a sample page composed in AsciiDoc

```
